apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "todo.server.name" .}}
  labels: {{include "todo.server.labels" . | nindent 4}}
data:
  GO_ENV: {{quote .Values.common.go_env}}
  LOG_LEVEL: {{quote .Values.common.log_level}}
  HTTP_SERVER_PORT: '3000'
  POSTGRES_HOST: {{quote .Values.server.postgres.host}}
  POSTGRES_PORT: {{quote .Values.server.postgres.port}}
  POSTGRES_USER: {{quote .Values.server.postgres.user}}
  POSTGRES_PASSWORD: {{quote .Values.server.postgres.password}}
  POSTGRES_DB_NAME: {{quote .Values.server.postgres.dbName}}
  POSTGRES_SSL_ENABLE: {{quote .Values.server.postgres.sslEnable}}
