apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{template "todo.middleware.name" .}}
  labels: {{include "todo.common.labels" . | nindent 4}}
spec:
  stripPrefix:
    prefixes:
      - /todo
