apiVersion: v1
kind: Service
metadata:
  name: {{template "todo.server.name" .}}
  labels: {{include "todo.server.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.server.port}}
      targetPort: 3000
      protocol: TCP
      name: http
  selector: {{include "todo.server.selectors" . | nindent 4}}
